### ISSUE TITLE
Improve the datalist forms

### ISSUE THREAD

**Issue by douglascrp** [sgirardin/easyContent2Metadata#9]
Both create and edit forms need some care.
Things like properties labels are not correct and the fields with LIST constraints are not configured as dropbox controls.

**Comment by sgirardin** [comment]
Hi douglas, could you be more specific?

**Comment by douglascrp** [comment]
I have just editted the comment.
I will try to do so until the end of the day.

**Comment by sgirardin** [comment]
Completely resolved with PR #15
